apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx2pods
spec:
  replicas: 2
  selector:
    matchLabels:
      env: prod
  template:
    metadata:
      labels:
        env: prod
    spec:
      containers:
      - name: nginx3container
        image: nginx
