apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx3pods
spec:
  replicas: 3
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
      - name: nginx3container
        image: nginx
