apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-1
  labels:
    run: use-pv
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: “/pv/data-analytics/q12”
